create table authorization (Login varchar(30) NOT NULL, KEY(Login), Password varchar(30) NOT NULL, Role varchar(50) NOT NULL, pib TEXT NOT NULL);

INSERT INTO authorization
(
  Login,
  Password,
  Role,
  pib
)
VALUES
(
'Savka',
'q1w2e3r4',
'Administrator',
'Pib'
);


create table Pregnant_data (
FirstName varchar(200) NOT NULL,
LastName varchar(200) NOT NULL,
FathersName varchar(200) NOT NULL,
DateOfBirtht DATE NOT NULL,
DateOfChildbirth DATE NOT NULL,
Diagnosis TEXT,
Drugs TEXT
);

create table Registry (
id 															MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PasportniDaniTitle											varchar(200),
PasportniDani												TEXT,
HistoryNumber    											TEXT,
Age															varchar(100),
Address														TEXT,
Proffesional    											varchar(200),
Disability													varchar(200),
ReceduvyTromboemboliiTitle									varchar(200),
ReceduvyTromboembolii   									varchar(200),
TromboemboliiAndEstrogens									varchar(200),
TromboemboliaSprovokovana									varchar(200),
SimeinuiAnamnezTromboembolii								varchar(200),
VstanovlennaTrombofilia										varchar(200),
SypytniZahvoryvanna											TEXT,
OldMore35													varchar(200),
Ogirinna													varchar(200),
VagitnistMore3												varchar(200),
Kyrinna														varchar(200),
VelykiVarikozniVenu											varchar(200),
ProvedennaProfTEYdpVagitnosti								varchar(200),
ElastychnaKompresia											TEXT,
MedukamentoznaProfilaktuka									varchar(200),
MedukamentoznaProfilaktukaNazvaPreperaty					TEXT,
MedukamentoznaProfilaktukaRegymPrujomy						TEXT,
HiryrgichneLikyvanna										TEXT,
TryvalistProvedennoiProfilaktyky							TEXT,
YskladneenaVidProfilaktyku									TEXT,
AkysherskiiAnamnez											varchar(200),
DanaVagitnist												varchar(200),
DanaVagitnistZaRahynkom  									varchar(200),
DaniPologuZaRahynkom										varchar(200),
PoperedniPologuZavershulus 									varchar(200),
PoperedniPologu												varchar(200),
NayavnistGuvyhDitey 										varchar(100),
VPerebigDannoiVagitnosti									varchar(100),
Vagitnist													varchar(100),
NaOblikyVGinochiiKonsyltacii								varchar(100),
ZagrozaPereruvannaVagitnosti								varchar(100),
ZagrozaPeredchasnuhPologiv									varchar(100),
ZagrozaPeredchasnuhPologivP4_1								varchar(100),
GestozIPolovunuVagitnosti									varchar(100),
InshiPruchynyZnevodnenna									TEXT,
GestozIIPolovunuVagitnosti									varchar(100),
GestozIIPolovunuVagitnostiVTermini							varchar(200),
VunuknennaTEY												varchar(100),
VudTEY														TEXT,
TEYTerminVagitnosti											varchar(200),
Bagatovodda													varchar(200),
BagatovoddaDiagnostovanoVTerminVagitnosti					varchar(200),
MaloVodda													varchar(200),
MaloVoddaDiagnostovanoVTerminVagitnosti						varchar(200),
DustressPloda												varchar(200),
ZatrumkaRozvutkyPloda										varchar(200),
NajavnistSustemnoiInfekcii 									varchar(200),
PatologiaPlacentu											varchar(200),
PatologiaLocalizaciiPlacentu    							varchar(200),
PeredchasneVadsharyvannaPlacentu							varchar(200),
HiryrgichniVtyrchannaPidChasVagitnosti						varchar(200),
TruvalaImmobilizacia										varchar(200),
ZavershennaDannoiVagitnosti									TEXT,
ProvedennaProfilaktukuTerapiiTEYPidChasVagitnosti			varchar(200),
PokazuDlaProvedennaProfilaktuky								TEXT,
ElastychnaKompresiaPynktVI									TEXT,
MedukamentoznaProfilaktukaPynktVI							TEXT,
MedukamentoznaProfilaktukaPynktVINazvaPreperaty				TEXT,
MedukamentoznaProfilaktukaPynktVIRegymPrujomy				TEXT,
MedukamentoznaProfilaktukaPynktVITerminKoluPruznacheno		TEXT,
HiryrgichneLikyvannaPynktVI									TEXT,
TryvalistProvedennoiProfilaktykyPynktVI						TEXT,
YskladneenaVidProfilaktykuPynktVI 							TEXT,
TerapiyVidminenoZaGodDoPologivPynktVI						varchar(200),
PerebigDanuhPologiv											varchar(200),
PologuVaginalni												varchar(200),
PologuAbdominalni											varchar(200),
PokazannaDlaAbdominalnogoRozrodjenna						TEXT,
PoryshennaPologovoiDialnosti								TEXT,
KorekciaAnomaliiPologovoiDialnosti							TEXT,
VuluvNavkoloplodovuhVod										varchar(200),
DustressPlodaVPologah										varchar(200),
GipotonichnaKrovotecha										varchar(200),
AnomaliiPrukriplennaPlacentu								varchar(200),
DefektPoslidy												varchar(200),
DefektObolonok												varchar(200),
AnomaliiPrukriplennaPypovunu								varchar(200),
OperatuvnaDopomoga											TEXT,
RozruvuPologovuhShlahiv										varchar(200),
EpizoAboPerineotomia										varchar(200),
KrovovtrataVPologah											TEXT,
TruvalistPologiv											varchar(200),
StanNovonarodgennogoTaNeoPeriodTitleLable					varchar(200),
Naroduvsa													varchar(200),
PruchunaMertvonarodgenna									varchar(200),
ZrilistNovonarodgennogo										varchar(200),
ParametruNovonarodgennogo									TEXT,
GipotrofiaPloda												varchar(200),
OcinkaZaShkaloyApgar										varchar(200),
NovonarodjenuiZVadamuRozvutky								TEXT,
PologovaTravma												TEXT,
SDR															varchar(200),
VnytrishnoytrobneInfikyvanna								varchar(200),
GemoragichniYskladnenna										varchar(200),
Anemia														varchar(200),
GiperBilirybinemia											TEXT,
Asfiksia													varchar(200),
PoryshennaKardioRespiratornoiAdaptacii						varchar(200),
VtrataMasuTila												TEXT,
VitaminKVvedeno												TEXT,
VupusanuiNa													TEXT,
NeonatalnaSmert												TEXT,
PruchunaSmertiZaRezyltatomAytopsii							TEXT,
PislapologovuiPeriod 										varchar(200),
PislapologovuiPerebig										varchar(200),
ProfilaktukaTerapiaTEYPynktI 								varchar(200),
ElastuchnaKompressiaPynktIX				  					TEXT,
MedukamentoznaProfilaktukaPynktIX   						TEXT,
MedukamentoznaProfilaktukaPynktIXNazvaPreparaty				TEXT,
MedukamentoznaProfilaktukaPynktIXRegumPrujomy				TEXT,
MedukamentoznaProfilaktukaPynktIXTerminKoluPruznacheno		TEXT,
HiryrgichneLikyvannaPynktIX									TEXT,
HiryrgichneLikyvannaPynktIXTerminNazvaOperacii				TEXT,
TruvalistProvedenoiProfilaktuktPynktIX						TEXT,
YskladnennaVidProfilaktukyPynktIX 							TEXT,
TromboembolichniYskladnennaPynktIX							TEXT,
TromboembolichniYskladnennaPynktIXVudTey					TEXT,
TromboembolichniYskladnennaPynktIXTerminVunuknenna			TEXT,
TromboembolichniYskladnennaPynktIXTerapiaTEY				TEXT,
MastutPynktIX                       						varchar(200),
SubinvolyciaMatkuPynktIX           							varchar(200),
EndometrutPynktIX                             				varchar(200),
PiznaPologovaKrovotechaPynktIX     							varchar(200),
SepsusPynktIX                         						varchar(200),
RoshodgennaShvivPynktIX          							varchar(200),
InshiPynktIX												TEXT,
HirVtyrchannaVPershi6TugnivPynktIX 							varchar(200),
VupuskaDodomyPynktIX               							varchar(200),
PerevedennaVInshuiStacionarPynktIX 							varchar(200),
ChangeDateRow												varchar(200),
WhoChangeRow												varchar(200)
);
